FORMAT: 1A
HOST: http://www.google.com

# MXcloud Generic
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Cellular
Notes related resources of the **Cellular API**

## Cellular Collection [/network/cellulars]
### List all Cellulars [GET]

The Collection response has following attributes:

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "enable": 1,
            "pinCode": "0000",
            "name": "wwan1",
            "username": "",
            "subnet": "255.255.255.252",
            "password": "",
            "authType": "PAP",
            "ip": "111.70.146.125",
            "enableAuth": 0,
            "gateway": "111.70.146.126",
            "signal": -96,
            "atPort": "/dev/ttyUSB1",
            "dns": ["168.95.1.1" , "168.95.192.1"],
            "status": 1,
            "apn": "internet",
            "operatorName": "Chunghwa Telecom",
            "modemPort": "/dev/cdc-wdm1"
          }
        ]

## Cellular [/network/cellulars/{id}]
A single Cellular object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Cellular to perform action with. Has example value.

### Retrieve an Cellular [GET]

The response for GET has following attributes:

- **id** (number, `1`): Identifier for an Cellular interface.
- **name** (string, `eth0`): Indicate the interface name.
- **modemPort** (string, `/dev/cdc-wcm1`): Internally use modem port device node
- **atPort** (string, `/dev/ttyUSB1`): Internally use AT port device node
- **ip** (IP address, `111.70.146.125`): IP address for the Cellular interface.
- **gateway** (IP address, `192.168.3.254`): Gateway is a router or a proxy server that routes between networks.
- **subnet** (IP address, `255.255.255.252`): Cellular network's subnet mask.
- **dns** (IP address array): The Domain Name System (DNS) is a hierarchical distributed naming system for computers, services, or any resource connected to the Internet or a private network.
- **enable** (number, `1`): Indicate the link status of Cellular interface should be set to up (`1`) or down (`0`).
- **pinCode** (string, `0000`): Use this code to auth when exits.
- **username** (string, ``): Indicate the username to enter pap/chap.
- **password** (string, ``): Indicate the password to enter pap/chap.
- **apn** (string, `internet`): Indicate apn of SIM card.
- **signal** (number, `99`): Indicate apn of SIM card.
- **enableAuth** (number, `0`): Indicate the authentication need to be done before dialUp
- **authType** (string, `PAP`): Indicate type of authentication such as 'PAP','CHAP'
- **status** (number, `0`): Indicate current status of connection, '0' / '1'
- **operatorName** (string, ``): Indicate current operator name if exit


+ Response 200 (application/json; charset=utf-8)

      {
        "id": 1,
        "enable": 1,
        "pinCode": "0000",
        "name": "wwan1",
        "username": "",
        "subnet": "255.255.255.252",
        "password": "",
        "authType": "PAP",
        "ip": "111.70.146.125",
        "enableAuth": 0,
        "gateway": "111.70.146.126",
        "signal": -96,
        "atPort": "/dev/ttyUSB1",
        "dns": ["168.95.1.1" , "168.95.192.1"],
        "status": 1,
        "apn": "internet",
        "operatorName": "Chunghwa Telecom",
        "modemPort": "/dev/cdc-wdm1"
      }


### Update an Cellular [PUT]

The request for PUT has following attributes:

- **id** (required, number, `1`): Identifier for an Cellular interface.
- **enable** (optional, number, `1`): Indicate the link status of Cellular interface should be set to up (`1`) or down (`0`).
- **pinCode** (optional, string, `0000`): Use this code to auth when exits.
- **username** (optional, string, ``): Indicate the username to enter pap/chap.
- **password** (optional, string, ``): Indicate the password to enter pap/chap.
- **apn** (optional, string, ``): Indicate apn of SIM card.
- **enableAuth** (optional, number, `0`): Indicate the authentication need to be done before dialUp
- **authType** (optional, string, ``): Indicate type of authentication such as 'PAP','CHAP'


The response for PUT is same as that for GET but:

- **restart** (optional, number, `0`): `1` means that view must be restarted after receiving the response.


The error response has following attributes:

- **status** (required, number, `1100`): Status code for error message.
- **message** (required, string): Error message in English.

+ Request (application/json)

      {
        "id": 1,
        "enable": 1,
        "pinCode": "0000",
        "username": "",
        "password": "",
        "authType": "PAP",
        "enableAuth": 0,
        "apn": "internet",
      }

+ Response 200 (application/json)

      {
        "id": 1,
        "enable": 1,
        "pinCode": "0000",
        "name": "wwan1",
        "username": "",
        "subnet": "255.255.255.252",
        "password": "",
        "authType": "PAP",
        "ip": "111.70.146.125",
        "enableAuth": 0,
        "gateway": "111.70.146.126",
        "signal": -96,
        "atPort": "/dev/ttyUSB1",
        "dns": ["168.95.1.1" , "168.95.192.1"],
        "status": 1,
        "apn": "internet",
        "operatorName": "Chunghwa Telecom",
        "modemPort": "/dev/cdc-wdm1"
      }

+ Response 400 (application/json)

      {
          "message": "Unable to apply!"
      }

# Group Ethernet
Notes related resources of the **Ethernet API**

## Ethernet Collection [/network/ethernets]
### List all Ethernets [GET]

The Collection response has following attributes:

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id":1,
                "wan":1,
                "name": "eth0",
                "ip": "192.168.3.127",
                "mac": "FF:FF:FF:FF:FF:FF",
                "netmask": "255.255.255.0",
                "subnet": "192.168.3.0",
                "gateway": "192.168.3.254",
                "dns":["8.8.8.8", "8.8.4.4"],
                "currentStatus":1,
                "enable":1,
                "enableDhcp":0
            },
            {
                "id":2,
                "wan":0,
                "name": "eth1",
                "ip": "192.168.3.127",
                "mac": "FF:FF:FF:FF:FF:FF",
                "netmask": "255.255.255.0",
                "subnet": "192.168.3.0",
                "gateway": "192.168.3.254",
                "dns":["8.8.8.8", "8.8.4.4"],
                "currentStatus":1,
                "enable":1,
                "enableDhcp":0
            }
        ]

### Update some Ethernets [PUT]

The collection request/response for update has following attributes:

+ Request (application/json; charset=utf-8)

        [
            {
                "id":2,
                "wan":0,
                "ip": "192.168.100.127",
                "netmask": "255.255.255.0",
                "subnet": "192.168.100.0",
                "gateway": "192.168.100.254",
                "dns":["8.8.8.8", "8.8.4.4"],
                "enable":1,
                "enableDhcp":0
            }
        ]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id":1,
                "wan":1,
                "name": "eth0",
                "ip": "192.168.3.127",
                "mac": "FF:FF:FF:FF:FF:FF",
                "netmask": "255.255.255.0",
                "subnet": "192.168.3.0",
                "gateway": "192.168.3.254",
                "dns":["8.8.8.8", "8.8.4.4"],
                "currentStatus":1,
                "enable":1,
                "enableDhcp":0
            },
            {
                "id":2,
                "wan":0,
                "name": "eth1",
                "ip": "192.168.100.127",
                "mac": "FF:FF:FF:FF:FF:FF",
                "netmask": "255.255.255.0",
                "subnet": "192.168.100.0",
                "gateway": "192.168.100.254",
                "dns":["8.8.8.8", "8.8.4.4"],
                "currentStatus":1,
                "enable":1,
                "enableDhcp":0,
                "restart":1
            }
        ]

## Ethernet [/network/ethernets/{id}]
A single Ethernet object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Ethernet to perform action with. Has example value.

### Retrieve an Ethernet [GET]

The response for GET has following attributes:

- **id** (required, number, `1`): Identifier for an Ethernet interface.
- **wan** (required, number, `1`, default `0`): Define the interface type is WAN (`1`) or LAN (`0`)
- **name** (required, string, `eth0`): Indicate the interface name.
- **ip** (required, IP address, `192.168.3.127`): IP address for the Ethernet interface.
- **mac** (required, MAC, `FF:FF:FF:FF:FF:FF`): The identical MAC address.
- **netmask** (required, IP address, `255.255.255.0`): Subnet mask for the Ethernet interface.
- **subnet** (required, IP address, `192.168.3.0`): A subnet (short for "subnetwork") is an identifiably separate part of an organization's network.
- **gateway** (required, IP address, `192.168.3.254`): Gateway is a router or a proxy server that routes between networks.
- **dns** (required, IP address array): The Domain Name System (DNS) is a hierarchical distributed naming system for computers, services, or any resource connected to the Internet or a private network.
- **currentStatus** (required, number `1`): Current status for the Ethernet interface, 0 for down and 1 for up.
- **enable** (required, number, `1`): Indicate the link status of Ethernet interface should be set to up (`1`) or down (`0`).
- **enableDhcp** (required, number, `0`): Enable (`1`) the dhcp client or using the static IP (`0`).

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "id":1,
                "wan":1,
                "name": "eth0",
                "ip": "192.168.3.127",
                "mac": "FF:FF:FF:FF:FF:FF",
                "netmask": "255.255.255.0",
                "subnet": "192.168.3.0",
                "gateway": "192.168.3.254",
                "dns":["8.8.8.8", "8.8.4.4"],
                "currentStatus":1,
                "enable":1,
                "enableDhcp":0
            }

### Update an Ethernet [PUT]

The request for PUT has following attributes:

- **wan** (optional, number, `1`, default `0`): Define the interface type is WAN (`1`) or LAN (`0`)
- **ip** (required, IP address, `192.168.3.127`): IP address for the Ethernet interface.
- **netmask** (required, IP address, `255.255.255.0`): Subnet mask for the Ethernet interface.
- **subnet** (required, IP address, `192.168.3.0`): A subnet (short for "subnetwork") is an identifiably separate part of an organization's network.
- **gateway** (optional, IP address, `192.168.3.254`): Gateway is a router or a proxy server that routes between networks.
- **dns** (optional, IP address array): The Domain Name System (DNS) is a hierarchical distributed naming system for computers, services, or any resource connected to the Internet or a private network.
- **enable** (required, number, `1`): Indicate the link status of Ethernet interface should be set to up (`1`) or down (`0`).
- **enableDhcp** (required, number, `0`): Enable (`1`) the dhcp client or using the static IP (`0`).

The response for PUT is same as that for GET.

The error response has following attributes:

- **status** (required, number, `1100`): Status code for error message.
- **message** (required, string): Error message in English.

+ Request (application/json; charset=utf-8)

        {
            "id": 2,
            "wan":0,
            "ip": "192.168.3.127",
            "netmask": "255.255.255.0",
            "subnet": "192.168.3.0",
            "gateway": "192.168.3.254",
            "dns":["8.8.8.8", "8.8.4.4"],
            "enable":1,
            "enableDhcp":0
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "id":2,
            "wan":0,
            "name": "eth1",
            "ip": "192.168.100.127",
            "mac": "FF:FF:FF:FF:FF:FF",
            "netmask": "255.255.255.0",
            "subnet": "192.168.100.0",
            "gateway": "192.168.100.254",
            "dns":["8.8.8.8", "8.8.4.4"],
            "currentStatus":1,
            "enable":1,
            "enableDhcp":0
        }

+ Response 404 (application/json; charset=utf-8)

        {
            "status": 2101,
            "message": "Interface not found!"
        }


# Group Firmware
Notes related resources of the **Firmware API**

## Firmware [/system/firmware]
The firmware information with all its details

### Retrieve the firmware information [GET]

The response for GET has following attributes:

- **version** (required, string, `1.0.0`): The firmware version.
- **server** (required, string, `www.moxa.com`): Server to download the latest version of firmware.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "version": "1.0.0",
                "server": "www.moxa.com"
            }

### Update the firmware [PUT]

The response for PUT has following attributes:

- **upgrade** (required, number, `1`): The system will start to do firmware upgrading.
- **server** (required, string, `www.moxa.com`): Server to download the latest version of firmware.

+ Request  (application/json)

        {
            "upgrade": 1,
            "server": "www.moxa.com"
        }

+ Response 200 (application/json)

        {
            "upgrade": 1,
            "server": "www.moxa.com"
        }

## Check Firmware Version [/system/firmware/check]
Check the firmware version

### Retrieve the current and candidate firmware version [GET]

The response for GET has following attributes:

- **current** (required, string, `1.1.0`): The current firmware version.
- **candidate** (required, string, `1.1.0`): The candidate firmware version.
- **isLatest** (required, integer, `0`): Is current version the latest or not.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
                "current": "1.0.0",
                "candidate": "1.1.0",
                "isLatest": 1
            }


# Group ImportExport
Notes related resources of the **ImportExport API**

## Import [/system/import]
The importexport object allows user to import/export configuration files to/from the system.

### Import the system [PUT]
The request for PUT has following attributes:

- **reboot** (optional, number, `3`): Reboot delay time in seconds.
- **file.url** (required, string, `3`): Reboot delay time in seconds.
- **file.headers** (optional, object): Headers for fetch the file if necessary.

+ Request  (application/json)

        {
          "id": 3,
          "resource": "/system/import",
          "method": "put",
          "data": {
            "reboot": 3,
            "file": {
              "url": "http://192.168.31.81:5000/api/v1/download/1234",
              "headers": {
                "accessToken": "MOXAMOXA-TEST-SYSTEM"
              }
            }
          }
        }

+ Response 200 (application/json)

        {}

## Export [/system/export]

### Export the system [GET]

The response for GET would be a file.
(From web to backend)

+ Request  (application/json)


+ Response 200 (application/octet-stream)

        ```binary data goes here```

### Export the system [POST]
(From backend to bundle)
The response for GET has following attributes:

+ Request  (application/json)

        {
          "url": "https://server/upload",
          "headers": {
            "accessToken": "MOXAMOXA-TEST-SYSTEM"
          }
        }

+ Response 200 (application/json)

        {
          "url": "https://server/upload/xxxxxxx"
        }


# Group Reboot
Notes related resources of the **Reboot API**

## Reboot [/system/reboot]
The reboot object allows user to reboot the system

### Reboot the system [PUT]

The response for PUT has following attributes:

- **enable** (required, number, `1`): Indicate the system will be reboot soon.

+ Request  (application/json)

        {
            "enable": 1
        }

+ Response 200 (application/json)

        {
            "enable": 1
        }

+ Response 404 (application/json)

        {
            "status": 1002,
            "message": "Resource busy!"
        }

# Group Time
Notes related resources of the **Time API**

## Time [/system/time]
The system time information include NTP client settings

### Retrieve system time information [GET]

The response for GET has following attributes:

- **time** (string, `2014-10-21 00:00:00`): Current system time. (iso 8601)
- **timezone** (string, `+08,00,0`): System timezone settings.
- **ntp.enable** (boolean, `enable`): Enable/Disable Ntp client.
- **ntp.server** (string, `pool.ntp.org`): Ntp server.
- **ntp.interval** (integer, `86400`): Ntp update interval in seconds. (at least: 60 seconds.)

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "time": "2015-03-26T16:27:48.611441Z",
                "timezone": "+08:00,0",
                "ntp": {
                    "enable": 1,
                    "server": "pool.ntp.org",
                    "interval": 86400
                }
            }

### Update system time properties [PUT]

The response for PUT has following attributes:

+ Request  (application/json; charset=utf-8)

    + Body

            {
                "time": "2015-03-26T16:27:48.611441Z",
                "timezone": "+08:00,0",
                "ntp": {
                    "enable": 0,
                    "server": "pool.ntp.org",
                    "interval": 86400
                }
            }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "time": "2015-03-26T16:27:48.611441Z",
                "timezone": "+08:00,0",
                "ntp": {
                    "enable": 1,
                    "server": "pool.ntp.org",
                    "interval": 86400
                }
            }

# Group SSH
Status related resources of the **SSH Service**

## SSH [/network/ssh]

### Retreive SSH Settings [GET]

The response for GET has following attributes:

- **enable** (required, integer, 1): enable ssh service

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "enable": 1
            }


### Update system time properties [PUT]

The response for PUT has following attributes:

- **enable** (required, integer, 1): enable ssh service

+ Request  (application/json; charset=utf-8)

        {
            "enable": 1
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "enable": 1
        }


# Group DNS
Notes related resources of the **DNS API**

## Current DNS [/network/dns]
### List DNS Settings [GET]

The response has following attributes:

- **interface** (optional, string): show the current dns corresponging interface
- **dns** (required, object array): show current running dns servers.

+ Response 200 (application/json; charset=utf-8)

        {
            "interface": "eth0",
            "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"]
        }

### Update DNS Settings [PUT]

+ Request  (application/json; charset=utf-8)

        {
            "interface": "eth0"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "interface": "eth0",
            "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"]
        }

+ Request  (application/json; charset=utf-8)

        {
            "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"]
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"]
        }

## DNS Database [/network/dns/db]
### List DNS Settings by Interfaces [GET]

The response has following attributes:

- **interface** (required, string): interface that dns servers belong to
- **dns** (required, object array): dns servers

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "interface": "eth0",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            },
            {
                "interface": "eth1",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            },
            {
                "interface": "wwlan0",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            }
        ]

### Update DNS Database [PUT]

+ Request  (application/json; charset=utf-8)

        {
            "interface": "eth0"
            "dns": ["8.8.8.8", "8.8.4.4"]
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "interface": "eth0"
            "dns": ["8.8.8.8", "8.8.4.4"]
        }

+ Request  (application/json; charset=utf-8)

        [
            {
                "interface": "eth0"
                "dns": ["8.8.8.8", "8.8.4.4"]
            },
            {
                "interface": "eth1",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            },
            {
                "interface": "wwlan0",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            }
        ]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "interface": "eth0"
                "dns": ["8.8.8.8", "8.8.4.4"]
            },
            {
                "interface": "eth1",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            },
            {
                "interface": "wwlan0",
                "dns": ["8.8.8.8", "8.8.4.4", "192.168.50.33"],
            }
        ]

## DNS Servers of Given Interface [/network/dns/{iface}]
### List DNS Servers of Given Interface [GET]

The response has following attributes:

- **dns** (required, object array): dns servers

+ Response 200 (application/json; charset=utf-8)

        ["8.8.8.8", "8.8.4.4", "192.168.50.33"]

### Update DNS Database by Interface [PUT]

+ Request  (application/json; charset=utf-8)

        ["8.8.8.8", "8.8.4.4", "192.168.50.33"]

+ Response 200 (application/json; charset=utf-8)

        ["8.8.8.8", "8.8.4.4", "192.168.50.33"]


# Group Status
Notes related resources of the **Status API**

## System status [/system/status]
### Get System Status data [GET]

The response has following attributes:

- **hostname** (required, string): show hostname
- **version** (required, string): show product version
- **uptime** (required, integer): show uptime of machine
- **diskUsage.total** (required, integer): show total storage size (unit: byte)
- **diskUsage.used** (required, integer): show used storage size (unit: byte)
- **diskUsage.free** (required, integer): show free storage size (unit: byte)
- **diskUsage.percent** (required, integer): show used storage percent


+ Response 200 (application/json; charset=utf-8)

        {
            "hostname": "Moxa",
            "version": "1.0.5-1",
            "uptimeSec": 312956,
            "diskUsage": {
                "total": 770695168,
                "used": 497655808,
                "free": 217038848,
                "percent": 64.6
            }
        }

### Set system hostname [PUT]

+ Request  (application/json; charset=utf-8)

        {
            "hostname": "moxa"
        }

+ Response 200 (application/json; charset=utf-8)

        {
            "hostname": "moxa"
        }


# Group Watchdog
Notes related resources of the **Watchdog API**

## Watchdog [/system/watchdog]
### List Watchdog Register Process [GET]

The response has following attributes:

- **process** (required, object array): list of register watchdog.

+ Response 200 (application/json)

        [
            {
                "id" : 1,
                "process" : "process name",
                "path" : "/usr/bin/process_name"
            }
            {
                "id" : 2,
                "process" : "process name",
                "path" : "/usr/bin/process_name"

            }
        ]

### Add Process to watchdog [PUT]


+ Request  (application/json)

        {
            "process": "process_name",
            "path": "/usr/bin/process_name"
        }


+ Response 200 (application/json)

        {
            "id": 1,
            "message": "success"
        }

+ Response 400 (application/json)

        {
            "id": 1,
            "message": "Process already register"
        }

### Delete Monitor Process from watchdog [DELETE]
/system/watchdog/1

+ Request  (application/json)

        {
            "process": "process_name"
        }


+ Response 200 (application/json)

        {
            "status": 200
        }


# Group IP Route
Notes related resources of the **IPRoute API**

## Available Interfaces [/network/routes/interfaces]
### List Available Interfaces [GET]

+ Response 200 (application/json)

        ["eth0", "eth1"]

## Default Gateway [/network/routes/default]
### Retrieve Default Gateway [GET]

The response has following attributes:

- **interface** (optional, string, `eth0`): interface to be set as the default gateway.
- **gateway** (optional, IP address, `192.168.31.254`): gateway address.

+ Response 200 (application/json)

        {
            "interface": "eth0",
            "gateway": "192.168.31.254"
        }

### Update Default Gateway [PUT]

The request and response has following attributes:

- **interface** (optional, string, `eth0`): interface to be set as the default gateway.
- **gateway** (optional, IP address, `192.168.31.254`): gateway address.

+ Request  (application/json)

        {}

+ Response 200 (application/json)

        {}

+ Request  (application/json)

        {
            "interface": "",
        }

+ Response 200 (application/json)

        {
            "interface": "",
        }

+ Request  (application/json)

        {
            "interface": "wwan0",
        }

+ Response 200 (application/json)

        {
            "interface": "wwan0",
            "gateway": "192.168.3.254"
        }

+ Response 404 (application/json)

        {
            "status": "40451",
            "message": "Update default gateway failed."
        }

## Default Gateway [/network/routes/secondary]
### Retrieve Secondary Default Gateway [GET]

The response has following attributes:

- **interface** (optional, string, `eth0`): interface to be set as the default gateway.
- **gateway** (optional, IP address, `192.168.31.254`): gateway address.

+ Response 200 (application/json)

        {
            "interface": "eth0",
            "gateway": "192.168.31.254"
        }

### Update Secondary Default Gateway [PUT]

The request and response has following attributes:

- **interface** (optional, string, `eth0`): interface to be set as the default gateway.
- **gateway** (optional, IP address, `192.168.31.254`): gateway address.

+ Request  (application/json)

        {}

+ Response 200 (application/json)

        {}

+ Request  (application/json)

        {
            "interface": "",
        }

+ Response 200 (application/json)

        {
            "interface": "",
        }

+ Request  (application/json)

        {
            "interface": "eth0",
        }

+ Response 200 (application/json)

        {
            "interface": "eth0",
            "gateway": "192.168.3.254"
        }

## Router Database [/network/routes/db]

### List Router Database by Interface [GET]

The response has following attributes:

- **interface** (optional, string, `eth0`): interface name.
- **gateway** (optional, IP address, `192.168.31.254`): gateway address.

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "interface": "eth0",
                "gateway": "192.168.3.254"
            },
            {
                "interface": "eth1",
                "gateway": "192.168.4.254"
            },
            {
                "interface": "wwlan0",
                "gateway": "192.168.5.254"
            }
        ]

### Update Router Database [PUT]

The request and response has following attributes:

- **interface** (optional, string, `eth0`): interface name.
- **gateway** (optional, IP address, `192.168.31.254`): gateway address.

+ Request  (application/json)

        {
            "interface": "eth1",
            "gateway": "192.168.4.254"
        }

+ Response 200 (application/json)

        {
            "interface": "eth1",
            "gateway": "192.168.4.254"
        }

+ Request  (application/json)

        [
            {
                "interface": "eth0",
                "gateway": "192.168.3.254"
            },
            {
                "interface": "eth1",
                "gateway": "192.168.4.254"
            },
            {
                "interface": "wwlan0",
                "gateway": "192.168.5.254"
            }
        ]

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "interface": "eth0",
                "gateway": "192.168.3.254"
            },
            {
                "interface": "eth1",
                "gateway": "192.168.4.254"
            },
            {
                "interface": "wwlan0",
                "gateway": "192.168.5.254"
            }
        ]

# Group Network
Notes related resources of the **network**

## Network Interface Information [/network/interfaces]
### Update the interface information [PUT]

The request for PUT has following attributes (this is an **event** message):

- **name** (required, string, `eth0`): Indicate the interface name.
- **ip** (required, IP address, `192.168.3.127`): IP address for the network interface.
- **netmask** (required, IP address, `255.255.255.0`): Subnet mask for the network interface.
- **subnet** (required, IP address, `192.168.3.0`): A subnet (short for "subnetwork") is an identifiably separate part of an organization's network.
- **gateway** (required, IP address, `192.168.3.254`): Gateway is a router or a proxy server that routes between networks.
- **dns** (required, IP address array): The Domain Name System (DNS) is a hierarchical distributed naming system for computers, services, or any resource connected to the Internet or a private network.

+ Request (application/json)

        {
            "name": "eth0",
            "ip":"192.168.3.127",
            "netmask":"255.255.255.0",
            "subnet":"192.168.3.0",
            "gateway":"192.168.3.254",
            "dns":["8.8.8.8", "8.8.4.4"],
        }

+ Response 200 (application/json)

        {
        }


# Group Serial Interface

## Serial Interface Collection [/system/serial]

A interface object has the following attributes:

- **id** (required, integer, `1`): Interface ID.
- **dev** (required, string, `ioLogik-E2210`): Device node path (readonly)
- **devDisplayName** (required, string, `ioLogik-E2210`): Display name (readonly)
- **mode** (required, string, `rs232`): Type of interface. Could be one of `rs232`, `rs485-2w`, `rs422/rs485-4w`

### Get all serial interfaces [GET]

+ Response 200 (application/json)

        [
            {
              "id": 1,
              "dev": "/dev/ttyM0",
              "devDisplayName": "PORT 1",
              "mode": "rs232"
            },
            {
              "id": 2,
              "dev": "/dev/ttyM1",
              "devDisplayName": "PORT 2",
              "mode": "rs485-2w"
            },
            {
              "id": 3,
              "dev": "/dev/ttyM2",
              "devDisplayName": "PORT 3",
              "mode": "rs422/rs485-4w"
            }
        ]

## Serial Interface [/system/serial/{id}]

+ Parameter
    + id: 1 (required, number) - ID of the Serial Interface in form of an integer

### Update a serial interface [PUT]

+ Request (application/json)

        {
            "mode": "rs485-2w"
        }

+ Response 200 (application/json)

        {
          "id": 1,
          "dev": "/dev/ttyM0",
          "devDisplayName": "PORT 1",
          "mode": "rs485-2w"
        }

# Group Serial Interface

## Serial Interface Collection [/system/serial]

A interface object has the following attributes:

- **id** (required, integer, `1`): Interface ID.
- **dev** (required, string, `ioLogik-E2210`): Device node path (readonly)
- **devDisplayName** (required, string, `ioLogik-E2210`): Display name (readonly)
- **mode** (required, string, `rs232`): Type of interface. Could be one of `rs232`, `rs485-2w`, `rs422/rs485-4w`

### Get all serial interfaces [GET]

+ Response 200 (application/json)

        [
            {
              "id": 1,
              "dev": "/dev/ttyM0",
              "devDisplayName": "PORT 1",
              "mode": "rs232"
            },
            {
              "id": 2,
              "dev": "/dev/ttyM1",
              "devDisplayName": "PORT 2",
              "mode": "rs485-2w"
            },
            {
              "id": 3,
              "dev": "/dev/ttyM2",
              "devDisplayName": "PORT 3",
              "mode": "rs422/rs485-4w"
            }
        ]

## Serial Interface [/system/serial/{id}]

+ Parameter
    + id: 1 (required, number) - ID of the Serial Interface in form of an integer

### Update a serial interface [PUT]

+ Request (application/json)

        {
            "mode": "rs485-2w"
        }

+ Response 200 (application/json)

        {
          "id": 1,
          "dev": "/dev/ttyM0"
          "devDisplayName": "PORT 1",
          "mode": "rs485-2w"
        }
        
# Group System Log

## System Log [/system/syslog]

### Download system logs [GET]

The response for GET would be a file.
(From web to backend)

+ Request  (application/json)

+ Response 200 (application/octet-stream)

        ```binary data goes here```

### Download system logs [POST]
(From backend to bundle)
The response for GET has following attributes:

+ Request  (application/json)

        {
          "url": "https://server/upload",
          "headers": {
            "accessToken": "MOXAMOXA-TEST-SYSTEM"
          }
        }

+ Response 200 (application/json)

        {
          "url": "https://server/upload/xxxxxxx"
        }
